<?php

  $setup->installNode("crm.campaign");
  $setup->installNode("crm.campaign_status");
  $setup->installNode("crm.campaign_type");
  $setup->installNode("crm.organization_relation");
  $setup->installNode("crm.organization_status");
  $setup->installNode("crm.industry");
  $setup->installNode("crm.former_name");
  $setup->installNode("crm.source");
  $setup->installNode("crm.relation_type");
  $setup->installNode("crm.rate");

  $setup->setVersion(1);

?>