<?php
  /* menu items */
  menuitem("setup","","main",true,700);    
  
  menuitem("support","","main",true,800);
     menuitem("achievo_docs", "manual.php", "support");
     menuitem("achievo_license", "license.php", "support");
     menuitem("achievo_home", "http://www.achievo.org/","support");  

  //menuitem("holiday_admin", dispatch_url("holidays", "admin"), "setup", array("activity", "admin"));
?>
