<?php
// Default information
$g_theme["Author"] = "Ivo Jansch"; // Author name
$g_theme["Author_email"] = "ivo@ibuildings.nl";  // Author e-mail
$g_theme["Description"] = "Achievo Classic";  // Theme description
$g_theme["Version"] = "1.0";  // version number
// some picture urls
$g_theme["BgURL"] = "";    // Background url
$g_theme["LogoURLl"] = "";  // Logo url
// Font settings
$g_theme["FontFamily"] = "Verdana, Helvetica, Arial"; // Font
$g_theme["FontSize"] = "10"; // Font size in pt.
$g_theme["FontWeight"] = "none";

// Font settings for a block
$g_theme["BlockFontFamily"] = "Verdana, Helvetica, Arial"; // Font
$g_theme["BlockFontSize"] = "10"; // Font size in pt.
$g_theme["BlockFontWeight"] = "none"; // FontWeight (bold) 
// Body settings
$g_theme["BgColor"] = "#b495bb"; // Background color
$g_theme["FgColor"] = "#000000"; // text color
// Link settings
$g_theme["LinkColor"] = "#000000"; // link color
$g_theme["HoverColor"] = "#000000"; // Hover color (IE4+ Only)
$g_theme["VisitedColor"] = "#000000"; // Visited color
$g_theme["ActiveColor"] = "#000000"; // Active color (IE4+ Only)
// Table header settings
$g_theme["TableHeaderFontFamily"] = "Verdana, Helvetica, Arial"; // Font
$g_theme["TableHeaderFontSize"] = "10"; // Font size in pt.
$g_theme["TableHeaderFontWeight"] = "Bold"; // FontWeight (bold) 
$g_theme["TableHeaderBgColor"] = "#cccccc"; // Table bgcolor;
$g_theme["TableHeaderFgColor"] = "#000000"; // Table font color;
// Table settings
$g_theme["TableFontFamily"] = "Verdana, Helvetica, Arial"; // Font
$g_theme["TableFontSize"] = "10"; // Font size in pt.
$g_theme["TableFontWeight"] = "none"; // FontWeight (bold) 
$g_theme["TableFgColor"] = "#000000"; // Table font color;
?>
