<?php

  $setup->installNode("organization.organization_relation");
  $setup->installNode("organization.organization_status");
  $setup->installNode("organization.industry");
  $setup->installNode("organization.former_name");
  $setup->installNode("organization.source");
  $setup->installNode("organization.relation_type");
  $setup->installNode("organization.rate");
  $setup->installNode("organization.campaign");
  $setup->installNode("organization.campaign_status");
  $setup->installNode("organization.campaign_type");
  $setup->installNode("organization.organization");

?>