<?php
$setup->createIndex('scheduler_dates','enddate',array('fields'=>array('enddate'=>array('sorting' => 'ascending',                                           
																																							'length' => ''                                                      
                                                                              ))));
                                                                              
?>