<?php
/**
 * Theme definition for achievo default theme
 *
 * @package achievo
 * @subpackage themes
 *
 * @author boy <boy@ibuildings.nl>
 *
 * @copyright (c) 2005 Ibuildings.nl BV
 * @license http://www.gnu.org/copyleft/gpl.html GNU General Public License 2
 *
 * @version $Revision$
 * $Id$
 */
/**
 * Theme definition
 */
$theme["customtpls"] = 'scan templates/';
$theme["graphBgColor"] = "#eeeeee";
$theme['compatible_menus'] = array('achievo');
?>