<?php

  $setup->installNode("project.activity");  
  $setup->installNode("project.phase");  
  $setup->installNode("project.phase_activity");  
  $setup->installNode("project.project");  
  $setup->installNode("project.project_personcontact");  
  $setup->installNode("project.project_personemployee");  
  $setup->installNode("project.role");  
  $setup->installNode("project.tpl_phase");  
  $setup->installNode("project.tpl_phase_activity");  
  $setup->installNode("project.tpl_project");  
  $setup->installNode("project.tpl_project_phase");  
  $setup->setVersion(1);

?>